pipeline {
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/tmtam612/clothes.git"
            }
        }
        stage("Build") {
            steps {
                dir("clothes") {
                    sh  "npm install"
                }
            }
        }
        stage('Test') {
            steps {
                dir("clothes") {
                    sh 'npm test'
                }
            }
        }
        stage('Deliver') { 
            steps {
                dir("clothes") {
                    sh  """
                        npm run build
                        npm start & sleep 1
                        """ 
                        input message: 'Finished using the web site? (Click "Proceed" to continue)'
                }
            }
        }
    }
}